//! Small DSP math: the phasor itself, pitch/gain conversions, smoothing.

use crate::Sample;

/// A unit-magnitude complex number rotated once per sample — the namesake of
/// the whole instrument. `e^{iωn}` generated by one complex multiply per
/// sample: simultaneously an oscillator (`sin`/`cos` for free), a quadrature
/// pair, and the seed of every phase trick in the book.
///
/// Numerical drift is corrected with one Newton step toward `|z| = 1` per
/// sample (`z *= 1.5 - 0.5·|z|²`), which keeps magnitude error below 1e-6
/// indefinitely without ever calling `sqrt`.
#[derive(Debug, Clone, Copy)]
pub struct Phasor {
    re: f64,
    im: f64,
    rot_re: f64,
    rot_im: f64,
}

impl Phasor {
    /// A phasor at angle 0 with the given rotation frequency.
    #[must_use]
    pub fn new(freq_hz: f64, sample_rate: f64) -> Self {
        let mut p = Self {
            re: 1.0,
            im: 0.0,
            rot_re: 1.0,
            rot_im: 0.0,
        };
        p.set_freq(freq_hz, sample_rate);
        p
    }

    /// Retune without resetting phase — glides stay click-free.
    pub fn set_freq(&mut self, freq_hz: f64, sample_rate: f64) {
        let w = core::f64::consts::TAU * freq_hz / sample_rate;
        self.rot_re = w.cos();
        self.rot_im = w.sin();
    }

    /// Advance one sample and return the sine component.
    #[inline]
    pub fn tick(&mut self) -> Sample {
        let re = self.re * self.rot_re - self.im * self.rot_im;
        let im = self.re * self.rot_im + self.im * self.rot_re;
        // One Newton step toward the unit circle.
        let mag2 = re * re + im * im;
        let k = 1.5 - 0.5 * mag2;
        self.re = re * k;
        self.im = im * k;
        self.im as Sample
    }

    /// Both quadrature components (`cos`, `sin`) at the current angle.
    #[inline]
    #[must_use]
    pub fn quadrature(&self) -> (Sample, Sample) {
        (self.re as Sample, self.im as Sample)
    }

    /// Reset to angle 0 (hard sync).
    pub fn reset(&mut self) {
        self.re = 1.0;
        self.im = 0.0;
    }
}

/// MIDI note number → frequency in Hz (A4 = 69 = 440 Hz, equal temperament).
#[must_use]
pub fn midi_to_hz(note: f32) -> f32 {
    440.0 * ((note - 69.0) / 12.0).exp2()
}

/// Decibels → linear gain.
#[must_use]
pub fn db_to_lin(db: f32) -> f32 {
    10.0f32.powf(db / 20.0)
}

/// Linear gain → decibels (floored at -120 dB so silence stays finite).
#[must_use]
pub fn lin_to_db(lin: f32) -> f32 {
    20.0 * lin.max(1e-6).log10()
}

/// One-pole parameter smoother: exponential approach to a target value.
/// Every user-facing continuous parameter goes through one of these — it is
/// the difference between a knob and a click.
#[derive(Debug, Clone, Copy)]
pub struct Smoothed {
    current: f32,
    target: f32,
    coeff: f32,
}

impl Smoothed {
    /// A smoother that covers ~63% of any jump in `time_ms`.
    #[must_use]
    pub fn new(value: f32, time_ms: f32, sample_rate: f32) -> Self {
        let coeff = 1.0 - (-1.0 / (time_ms * 1e-3 * sample_rate)).exp();
        Self {
            current: value,
            target: value,
            coeff,
        }
    }

    /// Set the value the smoother glides toward.
    pub fn set(&mut self, target: f32) {
        self.target = target;
    }

    /// Jump immediately (initialization, non-audible contexts).
    pub fn snap(&mut self, value: f32) {
        self.current = value;
        self.target = value;
    }

    /// Advance one sample.
    #[inline]
    pub fn tick(&mut self) -> f32 {
        self.current += self.coeff * (self.target - self.current);
        self.current
    }

    /// Current (smoothed) value without advancing.
    #[must_use]
    pub fn get(&self) -> f32 {
        self.current
    }
}

/// Flush a float that has decayed into the denormal range to exactly zero.
/// Called on filter/envelope state at block boundaries: denormal arithmetic
/// is catastrophically slow on some CPUs and wasm inherits the host's FPU.
#[inline]
#[must_use]
pub fn flush_denormal(x: f32) -> f32 {
    if x.abs() < 1e-30 {
        0.0
    } else {
        x
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_relative_eq;

    #[test]
    fn phasor_matches_sin_over_a_second() {
        let sr = 48_000.0;
        let f = 441.0;
        let mut p = Phasor::new(f, sr);
        let mut max_err = 0.0f64;
        for n in 0..48_000 {
            let got = f64::from(p.tick());
            let want = (core::f64::consts::TAU * f * f64::from(n + 1) / sr).sin();
            max_err = max_err.max((got - want).abs());
        }
        assert!(max_err < 1e-4, "phasor drifted from sin: max err {max_err}");
    }

    #[test]
    fn phasor_magnitude_stays_unit() {
        let mut p = Phasor::new(12_345.0, 48_000.0);
        for _ in 0..1_000_000 {
            p.tick();
        }
        let (re, im) = p.quadrature();
        let mag = f64::from(re).hypot(f64::from(im));
        assert_relative_eq!(mag, 1.0, epsilon = 1e-5);
    }

    #[test]
    fn midi_pitch_anchors() {
        assert_relative_eq!(midi_to_hz(69.0), 440.0, epsilon = 1e-3);
        assert_relative_eq!(midi_to_hz(57.0), 220.0, epsilon = 1e-3);
        assert_relative_eq!(midi_to_hz(60.0), 261.6256, epsilon = 1e-2);
    }

    #[test]
    fn smoother_converges_monotonically() {
        let mut s = Smoothed::new(0.0, 5.0, 48_000.0);
        s.set(1.0);
        let mut last = 0.0;
        for _ in 0..48_000 {
            let v = s.tick();
            assert!(v >= last, "smoother must be monotone on a step");
            last = v;
        }
        assert!(last > 0.999);
    }
}
